version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3004:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      args:
        - HF_TOKEN=${HF_TOKEN}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - HF_TOKEN=${HF_TOKEN}
